# Generated by Django 2.1.2 on 2018-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('http_cookie', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('server_name', models.CharField(blank=True, max_length=200, null=True)),
                ('post_url', models.CharField(blank=True, max_length=20)),
                ('visit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('post_url', models.CharField(blank=True, max_length=15)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
    ]
